apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
   annotations:
    # The email notifier must be configured in argocd-notifications-cm.yaml, The `.email` is the name of the notifier, i.e, `service.email` in the argocd-notifications-cm.yaml.
    # Subscribe to notifications when the app health is degraded.
    notifications.argoproj.io/subscribe.on-health-degraded.email: "heeni.patel@gmail.com"  # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
    # Subscribe to notifications when the app is successfully deployed.
    notifications.argoproj.io/subscribe.on-deployed.email: "heeni.patel@gmail.com" # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>" 
spec:
  project: default

  source:
    repoURL: https://github.com/kp0220/Azure_Ubuntu_Kind_Traefik_Argocd_Let-s-encrypt.git
    targetRevision: main
    path: App_Deploy_Using_Argocd_Online-Shop

  destination:
    server: https://172.18.0.4:6443
    namespace: online-shop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

