deployment:
  kind: Deployment

service:
  enabled: true

  spec:
    type: NodePort

ports:
  web:
    port: 8000
    exposedPort: 80
    nodePort: 30080
    protocol: TCP

    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    port: 8443
    exposedPort: 443
    nodePort: 30443
    protocol: TCP

    http:
      tls:
        enabled: true

